export enum DispatchStatus {
  REQUESTED = 'REQUESTED',
  SEARCHING = 'SEARCHING',
  OFFERING = 'OFFERING',
  ASSIGNED = 'ASSIGNED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}
